import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import { Col, Row } from 'react-bootstrap'
import styles from '../styles/Home.module.css'

export default function Home() {

  const [textField, setTextField] = useState('')
  const [isPalindrome, setIsPalindrome] = useState(false);

  const palindromeChecker = async (e) => {
       e.preventDefault();
       const inputText = {
         name: e.target.name.value
       }
       setTextField(inputText.name);

       const reversedText = inputText.name.split('').reverse().join('');
       if(inputText.name === reversedText){
          setIsPalindrome(true);
       }else{
        setIsPalindrome(false);
       }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <Row className='justify-content-center'>  
         <Col md={10} border border-secondary rounded>
             <form onSubmit={palindromeChecker}>
               <label htmlFor="name">Write your text</label>
               <input type="text" id='name' autoComplete='name' placeholder='Write your text here' className='form-control'/>
               <button type='submit' className='btn btn-secondary'>Submit</button>
             </form>
             <div className='mt-3 border border-secondary'>
                 {
                   isPalindrome === true && textField != '' ? <h4 className='text-success'>Yah, It is palindrome!</h4>
                    : (isPalindrome === false && textField != '') && <h4 className='text-danger'>Sorry, It is not palindrome!</h4>
                  }
             </div>
         </Col>
       </Row>
      </main>

      <footer className={styles.footer}>
       
        <a
          href="https://mohiuddin-mazumder.web.app/"
          target="_blank"
          rel="noopener noreferrer"
        >
         © 2022 Mohiuddin Mazumder. All Rights Reserved.
          
        </a>
        
      </footer>
    </div>
  )
}
