import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [textField, setTextField] = useState('')
  const [isPalindrome, setIsPalindrome] = useState(false);

  const palindromeChecker = async (e) => {
       e.preventDefault();
       const inputText = {
         name: e.target.name.value
       }
       setTextField(inputText.name);

       const reversedText = inputText.name.split('').reverse().join('');
       if(inputText.name === reversedText){
          setIsPalindrome(true);
       }else{
        setIsPalindrome(false);
       }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <div className='justify-content-center'>  
         <div >
           <div className='border border-secondary rounded p-4'>
             <h2 className='text-3xl text-green-600 p-2'>Palindrome Checker</h2>
              <form onSubmit={palindromeChecker}>
                <label htmlFor="name">Write your text</label>
                <textarea type="text" id='name' autoComplete='name' placeholder='Write your text here' className='form-control'/>
                <button type='submit' variant="secondary">Submit</button>
              </form>
              <div className='mt-3 border border-secondary'>
                  {
                    isPalindrome === true && textField != '' ? <h4 className='text-success'>Yah, It&apos;s a palindrome!</h4>
                      : (isPalindrome === false && textField != '') && <h4 className='text-danger'>Sorry, that&apos;s not a palindrome.</h4>
                    }
              </div> 
           </div>
            
         </div>
       </div>
      </main>

      <footer className={styles.footer}>
       
        <a
          href="https://mohiuddin-mazumder.web.app/"
          target="_blank"
          rel="noopener noreferrer"
        >
         © 2022 Mohiuddin Mazumder. All Rights Reserved.
          
        </a>
        
      </footer>
    </div>
  )
}
